// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedaVisite.Services.database;

#nullable disable

namespace SchedaVisite.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260429071438_AnamnesiGeriatrica")]
    partial class AnamnesiGeriatrica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("SchedaVisite.Models.Patient", b =>
                {
                    b.Property<string>("PatientCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientCode");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SchedaVisite.Models.Visit", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Appetite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AssistanceAlone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssistanceFamilyMembers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssistanceSpouse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bpsd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CareTaker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CognitiveDeficit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Constipation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dysphagia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Falls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HearingImpairment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotorSkill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NutrionalProblems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Telemedicina")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("VisualImpairment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WalkingType")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightLoss")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VisitCode");

                    b.HasIndex("PatientCode");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("SchedaVisite.Models.Visit", b =>
                {
                    b.HasOne("SchedaVisite.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SchedaVisite.Models.Patient", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
