// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedaVisite.Services.database;

#nullable disable

namespace SchedaVisite.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260509095058_APR0")]
    partial class APR0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("SchedaVisite.Models.Patient", b =>
                {
                    b.Property<string>("PatientCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientCode");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SchedaVisite.Models.Visit", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Amyloidosis")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AmyloidosisDiagnosisDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AmyloidosisDmt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AmyloidosisTherapyStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmyloidosisType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Anemia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Appetite")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArterialHypertension")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssistanceAlone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssistanceFamilyMembers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssistanceSpouse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AtrialFibrillation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bpsd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bradycardia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CareTaker")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CerebrovascularDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChronicKidneyDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChronicObstructivePulmonaryDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChronicSkinUlcers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CognitiveDeficit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Constipation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dementia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DementiaType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dysphagia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Falls")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HearingImpairment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HeartFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HeparinUseLast6Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HipFracture")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HospitalizationLast6Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IschemicHeartDisease")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotorSkill")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Neoplasm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeuromuscularDisorders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nights")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NutrionalProblems")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OxygenTherapyLast6Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Parkinson")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PeripheralVascularDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Schizophrenia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseIao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseIm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseItr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseSao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseSm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Telemedicina")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VisualImpairment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WalkingType")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightLoss")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitCode");

                    b.HasIndex("PatientCode");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("SchedaVisite.Models.VisitPersistedTexts", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("AprText")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitsPersistedTexts");
                });

            modelBuilder.Entity("SchedaVisite.Models.Visit", b =>
                {
                    b.HasOne("SchedaVisite.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientCode");

                    b.HasOne("SchedaVisite.Models.VisitPersistedTexts", "VisitPersistedTexts")
                        .WithOne("Visit")
                        .HasForeignKey("SchedaVisite.Models.Visit", "VisitCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("VisitPersistedTexts");
                });

            modelBuilder.Entity("SchedaVisite.Models.Patient", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("SchedaVisite.Models.VisitPersistedTexts", b =>
                {
                    b.Navigation("Visit");
                });
#pragma warning restore 612, 618
        }
    }
}
