// <auto-generated />
using System;
using CardiogeriatriaHSG.Services.database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardiogeriatriaHSG.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260513181235_TD0")]
    partial class TD0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("CardiogeriatriaHSG.Models.Patient", b =>
                {
                    b.Property<string>("PatientCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientCode");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.Visit", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Telemedicina")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitCode");

                    b.HasIndex("PatientCode");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitAg", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Appetite")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AssistanceAlone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssistanceFamilyMembers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssistanceSpouse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bpsd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CareTaker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CognitiveDeficit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Constipation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dysphagia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Falls")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HearingImpairment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotorSkill")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nights")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NutrionalProblems")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VisualImpairment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WalkingType")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightLoss")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitAg");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitApr", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Amyloidosis")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AmyloidosisDiagnosisDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AmyloidosisDmt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AmyloidosisTherapyStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmyloidosisType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Anemia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AprText")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArterialHypertension")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AtrialFibrillation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bradycardia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CerebrovascularDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChronicKidneyDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChronicObstructivePulmonaryDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChronicSkinUlcers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dementia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DementiaType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HeartFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HeparinUseLast6Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HipFracture")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HospitalizationLast6Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IschemicHeartDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Neoplasm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeuromuscularDisorders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OxygenTherapyLast6Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Parkinson")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PeripheralVascularDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Schizophrenia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseIao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseIm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseItr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseSao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseSm")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitApr");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitTd", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AceInhibitor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acetazolamide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcheInhibitorOrMemantine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acoramidis")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Antidepressants")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Antipsychotics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Arb")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Arni")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Benzodiazepines")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BetaBlocker")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CalciumChannelBlockers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Clonidine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Doac")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Doxazosin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ezetimibe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Fibrates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Furosemide")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FurosemideDose")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Glp1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hydrochlorothiazide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LowDoseTrazodone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mra")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Nitrates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opioids")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OtherAnalgesics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OtherLoopDiuretic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paracetamol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PhysicalExercise")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ppi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProteinSupplementation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ranolazine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sglt2Inhibitor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Statins")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tafamidis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TdText")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vericiguat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vka")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vutrisiran")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZDrugs")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitTd");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.Visit", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientCode");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitAg", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitAg")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitAg", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitApr", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitApr")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitApr", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitTd", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitTd")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitTd", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.Patient", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.Visit", b =>
                {
                    b.Navigation("VisitAg");

                    b.Navigation("VisitApr");

                    b.Navigation("VisitTd");
                });
#pragma warning restore 612, 618
        }
    }
}
