// <auto-generated />
using System;
using CardiogeriatriaHSG.Services.database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardiogeriatriaHSG.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260731064428_TFV1")]
    partial class TFV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CardiogeriatriaHSG.Models.Patient", b =>
                {
                    b.Property<string>("PatientCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientManualText")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientCode");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.Visit", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Telemedicina")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitCode");

                    b.HasIndex("PatientCode");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitAg", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgManualText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Appetite")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AssistanceAlone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssistanceFamilyMembers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssistanceSpouse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bpsd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CareTaker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CognitiveDeficit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Constipation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dysphagia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Falls")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HearingImpairment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotorSkill")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nights")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NutritionalProblems")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VisualImpairment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WalkingType")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightLoss")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitAg");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitApr", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Amyloidosis")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AmyloidosisDiagnosisDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AmyloidosisDmt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AmyloidosisTherapyStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmyloidosisType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Anemia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AprText")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArterialHypertension")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AtrialFibrillation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bradycardia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CerebrovascularDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChronicKidneyDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChronicObstructivePulmonaryDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChronicSkinUlcers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dementia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DementiaType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HeartFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HeparinUseLast6Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HipFracture")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HospitalizationLast6Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IschemicHeartDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Neoplasm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeuromuscularDisorders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OxygenTherapyLast6Months")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Parkinson")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PeripheralVascularDisease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Schizophrenia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseIao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseIm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseItr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseSao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SevereValvularDiseaseSm")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitApr");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitCga", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Car")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cfs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CgaManualText")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Continence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cooking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Diet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dressing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eft")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Es")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Handgrip")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Height")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HouseholdChores")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hygiene")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Kccq")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Laundry")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Medicines")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Mmse")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Moca")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Necpal4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OtherNeurologicalDiseases")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Phone")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PostSppbBorg")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PosturalPassages")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestingBorg")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SenseOfMoney")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Shopping")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Shower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SppbBalance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("SppbFourMetersTime")
                        .HasColumnType("REAL");

                    b.Property<string>("SppbSitToStand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SurpriseQuestion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitCga");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitCo", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoText")
                        .HasColumnType("TEXT");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitCo");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitEco", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("BLines")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CoalescentBLines")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ConsiderationBLines")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EcoManualText")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("GradientDistributionBLines")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IrregularPleuralLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IvcCollapsibility")
                        .HasColumnType("TEXT");

                    b.Property<string>("IvcDiameter")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeftPefs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MeasurableIvc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PatternA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PleuralLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortalVeinPulsatility")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RightPefs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Vexus")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitEco");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitEe", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<float?>("Albumin")
                        .HasColumnType("REAL");

                    b.Property<float?>("Albuminuria")
                        .HasColumnType("REAL");

                    b.Property<float?>("Bnp")
                        .HasColumnType("REAL");

                    b.Property<float?>("Creatinine")
                        .HasColumnType("REAL");

                    b.Property<string>("EeManualText")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExamDate")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Hemoglobin")
                        .HasColumnType("REAL");

                    b.Property<float?>("NtProBnp")
                        .HasColumnType("REAL");

                    b.Property<float?>("Potassium")
                        .HasColumnType("REAL");

                    b.Property<float?>("Sodium")
                        .HasColumnType("REAL");

                    b.Property<float?>("Urea")
                        .HasColumnType("REAL");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitEe");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitEo", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChestMv")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChestNoises")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DependentEdema")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DependentEdemaFovea")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependentEdemaLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependentEdemaType")
                        .HasColumnType("TEXT");

                    b.Property<string>("EoManualText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeartSoundPauses")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartSoundRhythm")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartSoundType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("JugularVenousDistension")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaximumBloodPressure")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumBloodPressure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OrthostaticHypotension")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PeripheralNeuropathy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Rheoencephalography")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitEo");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitRc", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AcuteStressLast3Months")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Angina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dyspnea")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmergenciesSinceLastVisit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmergenciesSinceLastVisitCause")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmergenciesSinceLastVisitNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FallsSinceLastVisit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FallsSinceLastVisitDiagnosis")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FallsSinceLastVisitNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FallsSinceLastVisitType")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FirstHospitalizationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HospitalizationsSinceLastVisit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HospitalizationsSinceLastVisitCause")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HospitalizationsSinceLastVisitDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HospitalizationsSinceLastVisitNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Palpitations")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ParoxysmalNocturnalDyspnea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RcManualText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reports")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SleepingSittingPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SleepingWithPillowsNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitRc");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitTd", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AceInhibitor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acetazolamide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcheInhibitorOrMemantine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acoramidis")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Amiodarone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Antidepressants")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Antipsychotics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Arb")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Arni")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Benzodiazepines")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BetaBlocker")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CalciumChannelBlockers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Clonidine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Doac")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Doxazosin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dpp4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ezetimibe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Fibrates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Furosemide")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FurosemideDose")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Glp1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hydrochlorothiazide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Insulin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LowDoseTrazodone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mra")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Nitrates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opioids")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OralHypoglycemicAgents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OtherAnalgesics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OtherLoopDiuretic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paracetamol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PhysicalExercise")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ppi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProteinSupplementation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ranolazine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sglt2Inhibitor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Statins")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tafamidis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TdText")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vericiguat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vka")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vutrisiran")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZDrugs")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitTd");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitTfv", b =>
                {
                    b.Property<string>("VisitCode")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AceInhibitor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acetazolamide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcheInhibitorOrMemantine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acoramidis")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Amiodarone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Antidepressants")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Antipsychotics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Arb")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Arni")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Benzodiazepines")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BetaBlocker")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CalciumChannelBlockers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Clonidine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Doac")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Doxazosin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dpp4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ezetimibe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Fibrates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Furosemide")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FurosemideDose")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Glp1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hydrochlorothiazide")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Insulin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LowDoseTrazodone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mra")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Nitrates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Opioids")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OralHypoglycemicAgents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OtherAnalgesics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OtherLoopDiuretic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paracetamol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PhysicalExercise")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ppi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProteinSupplementation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ranolazine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sglt2Inhibitor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Statins")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tafamidis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TfvText")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vericiguat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vka")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vutrisiran")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZDrugs")
                        .HasColumnType("INTEGER");

                    b.HasKey("VisitCode");

                    b.ToTable("VisitTfv");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.Visit", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientCode");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitAg", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitAg")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitAg", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitApr", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitApr")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitApr", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitCga", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitCga")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitCga", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitCo", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitCo")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitCo", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitEco", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitEco")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitEco", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitEe", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitEe")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitEe", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitEo", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitEo")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitEo", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitRc", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitRc")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitRc", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitTd", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitTd")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitTd", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.VisitTfv", b =>
                {
                    b.HasOne("CardiogeriatriaHSG.Models.Visit", "Visit")
                        .WithOne("VisitTfv")
                        .HasForeignKey("CardiogeriatriaHSG.Models.VisitTfv", "VisitCode");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.Patient", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("CardiogeriatriaHSG.Models.Visit", b =>
                {
                    b.Navigation("VisitAg");

                    b.Navigation("VisitApr");

                    b.Navigation("VisitCga");

                    b.Navigation("VisitCo");

                    b.Navigation("VisitEco");

                    b.Navigation("VisitEe");

                    b.Navigation("VisitEo");

                    b.Navigation("VisitRc");

                    b.Navigation("VisitTd");

                    b.Navigation("VisitTfv");
                });
#pragma warning restore 612, 618
        }
    }
}
